baseURL = 'https://kishorpokharel.github.io/hugo-example-site/'
languageCode = 'en-us'
title = 'MySite'
minify = true

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = ''
  weight = 10
[[menu.main]]
  name = 'Posts'
  pageRef = 'posts'
  weight = 20
[[menu.main]]
  name = 'Search'
  pageRef = 'search'
  weight = 30

[outputs]
	home = ["HTML","RSS","JSON"]
